"use client";

import type { Artifact, JobDetail } from "@/types/telemetry";

interface StreamViewerProps {
  job: JobDetail | null;
  subjectName?: string;
  artifactContentUrl(artifactId: string): string;
  /** Stack the panels vertically instead of side by side (for narrow columns). */
  stacked?: boolean;
}

export function StreamViewer({
  job,
  subjectName = "Subject",
  artifactContentUrl,
  stacked = false,
}: StreamViewerProps) {
  const annotated = latestArtifact(job?.artifacts, "annotated_frame");
  const raw =
    job?.artifacts.find(
      (artifact) =>
        artifact.kind === "frame" && artifact.frameIndex === annotated?.frameIndex,
    ) ?? latestArtifact(job?.artifacts, "frame");
  const best = bestPerson(job);

  return (
    <section className={`grid gap-3 ${stacked ? "grid-cols-1" : "md:grid-cols-2"}`}>
      <FeedPanel
        title="Source frame"
        artifact={raw}
        artifactContentUrl={artifactContentUrl}
        emptyLabel={jobMessage(job, "Extracting frames from sortie…")}
        jobId={job?.id}
      />
      <FeedPanel
        title={annotated ? `${subjectName} located` : "Detection evidence"}
        artifact={annotated}
        artifactContentUrl={artifactContentUrl}
        emptyLabel={jobMessage(job, "Running SAHI + YOLO person search…")}
        jobId={job?.id}
        highlight={Boolean(annotated)}
        footer={
          best
            ? `PERSON ${(best.confidence * 100).toFixed(0)}% · CLOTHING ${(
                (best.clothingMatchScore ?? 0) * 100
              ).toFixed(0)}%`
            : undefined
        }
      />
    </section>
  );
}

function FeedPanel({
  title,
  artifact,
  artifactContentUrl,
  emptyLabel,
  jobId,
  highlight = false,
  footer,
}: {
  title: string;
  artifact?: Artifact;
  artifactContentUrl(artifactId: string): string;
  emptyLabel: string;
  jobId?: string | null;
  highlight?: boolean;
  footer?: string;
}) {
  return (
    <div
      className={`overflow-hidden rounded-lg border bg-surface-raised shadow-panel ${
        highlight ? "border-accent-400/60 shadow-glow" : "border-line"
      }`}
    >
      <header className="flex items-center justify-between gap-2 border-b border-line-soft px-4 py-2.5">
        <h3
          className={`text-[15px] font-semibold tracking-tight ${
            highlight ? "text-accent-300" : "text-ink-100"
          }`}
        >
          {title}
        </h3>
        <span className="shrink-0 font-mono text-[11px] uppercase tracking-label text-ink-500">
          {jobId ? `Job ${jobId.slice(0, 8)}` : "Standby"}
        </span>
      </header>
      <div className="relative flex aspect-video items-center justify-center bg-black/75">
        {artifact ? (
          // Artifact URLs are generated by our own API and retain their original dimensions.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={artifactContentUrl(artifact.id)}
            alt={`${title} from analyzed sortie`}
            className="h-full w-full object-contain"
          />
        ) : (
          <div className="space-y-3 px-5 text-center">
            <div className="mx-auto h-1 w-24 overflow-hidden rounded-full bg-surface-sunken">
              <div className="h-full w-1/2 animate-pulse rounded-full bg-status-searching" />
            </div>
            <p className="text-[13px] text-ink-400">{emptyLabel}</p>
          </div>
        )}
      </div>
      {footer ? (
        <footer className="flex items-center gap-2 border-t border-status-confirmed/30 bg-status-confirmed/[0.08] px-4 py-2 font-mono text-[11px] uppercase tracking-label text-status-confirmed">
          <span className="h-1.5 w-1.5 rounded-full bg-current" aria-hidden />
          Subject found · {footer}
        </footer>
      ) : null}
    </div>
  );
}

function latestArtifact(
  artifacts: Artifact[] | undefined,
  kind: Artifact["kind"],
): Artifact | undefined {
  return [...(artifacts ?? [])].reverse().find((artifact) => artifact.kind === kind);
}

function bestPerson(job: JobDetail | null) {
  const people = (job?.detections ?? []).filter(
    (detection) => detection.className === "person",
  );
  return people.reduce<(typeof people)[number] | undefined>(
    (best, current) =>
      !best ||
      (current.clothingMatchScore ?? 0) > (best.clothingMatchScore ?? 0)
        ? current
        : best,
    undefined,
  );
}

function jobMessage(job: JobDetail | null, processing: string): string {
  if (!job) {
    return "Attach a recorded sortie to begin analysis";
  }
  if (job.status === "failed") {
    return job.failureReason ?? "Analysis failed";
  }
  if (job.status === "completed" && job.detections.length === 0) {
    return "Analysis complete — no person detected";
  }
  return processing;
}
