"use client";

import type { Artifact, JobDetail } from "@/types/telemetry";

interface StreamViewerProps {
  job: JobDetail | null;
  subjectName?: string;
  artifactContentUrl(artifactId: string): string;
}

export function StreamViewer({
  job,
  subjectName = "Subject",
  artifactContentUrl,
}: StreamViewerProps) {
  const annotated = latestArtifact(job?.artifacts, "annotated_frame");
  const raw =
    job?.artifacts.find(
      (artifact) =>
        artifact.kind === "frame" && artifact.frameIndex === annotated?.frameIndex,
    ) ?? latestArtifact(job?.artifacts, "frame");
  const best = bestPerson(job);

  return (
    <section className="grid gap-3 md:grid-cols-2">
      <FeedPanel
        title="Source frame"
        artifact={raw}
        artifactContentUrl={artifactContentUrl}
        emptyLabel={jobMessage(job, "Extracting frames from sortie…")}
        jobId={job?.id}
      />
      <FeedPanel
        title={annotated ? `${subjectName} located` : "Detection evidence"}
        artifact={annotated}
        artifactContentUrl={artifactContentUrl}
        emptyLabel={jobMessage(job, "Running SAHI + YOLO person search…")}
        jobId={job?.id}
        highlight={Boolean(annotated)}
        footer={
          best
            ? `PERSON ${(best.confidence * 100).toFixed(0)}% · CLOTHING ${(
                (best.clothingMatchScore ?? 0) * 100
              ).toFixed(0)}%`
            : undefined
        }
      />
    </section>
  );
}

function FeedPanel({
  title,
  artifact,
  artifactContentUrl,
  emptyLabel,
  jobId,
  highlight = false,
  footer,
}: {
  title: string;
  artifact?: Artifact;
  artifactContentUrl(artifactId: string): string;
  emptyLabel: string;
  jobId?: string | null;
  highlight?: boolean;
  footer?: string;
}) {
  return (
    <div
      className={`overflow-hidden rounded-lg border bg-tactical-800 ${
        highlight ? "border-amber-500 shadow-[0_0_24px_rgba(240,193,75,0.14)]" : "border-olive-700"
      }`}
    >
      <header className="flex items-center justify-between border-b border-olive-800 px-3 py-2">
        <h3
          className={`font-mono text-xs uppercase tracking-widest ${
            highlight ? "text-amber-300" : "text-olive-200"
          }`}
        >
          {title}
        </h3>
        <span className="font-mono text-[10px] text-olive-500">
          {jobId ? `JOB ${jobId.slice(0, 8)}` : "STANDBY"}
        </span>
      </header>
      <div className="relative flex aspect-video items-center justify-center bg-black/75">
        {artifact ? (
          // Artifact URLs are generated by our own API and retain their original dimensions.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={artifactContentUrl(artifact.id)}
            alt={`${title} from analyzed sortie`}
            className="h-full w-full object-contain"
          />
        ) : (
          <div className="space-y-3 px-5 text-center">
            <div className="mx-auto h-1 w-24 overflow-hidden rounded bg-olive-900">
              <div className="h-full w-1/2 animate-pulse rounded bg-amber-400" />
            </div>
            <p className="font-mono text-xs text-olive-400">{emptyLabel}</p>
          </div>
        )}
      </div>
      {footer ? (
        <footer className="border-t border-amber-900 bg-amber-950/60 px-3 py-2 font-mono text-[10px] tracking-wider text-amber-200">
          SUBJECT FOUND · {footer}
        </footer>
      ) : null}
    </div>
  );
}

function latestArtifact(
  artifacts: Artifact[] | undefined,
  kind: Artifact["kind"],
): Artifact | undefined {
  return [...(artifacts ?? [])].reverse().find((artifact) => artifact.kind === kind);
}

function bestPerson(job: JobDetail | null) {
  const people = (job?.detections ?? []).filter(
    (detection) => detection.className === "person",
  );
  return people.reduce<(typeof people)[number] | undefined>(
    (best, current) =>
      !best ||
      (current.clothingMatchScore ?? 0) > (best.clothingMatchScore ?? 0)
        ? current
        : best,
    undefined,
  );
}

function jobMessage(job: JobDetail | null, processing: string): string {
  if (!job) {
    return "Attach a recorded sortie to begin analysis";
  }
  if (job.status === "failed") {
    return job.failureReason ?? "Analysis failed";
  }
  if (job.status === "completed" && job.detections.length === 0) {
    return "Analysis complete — no person detected";
  }
  return processing;
}
